### ISSUE TITLE
Repo License?

### ISSUE THREAD

**Issue by joeyballentine** [yongliuy/DITN#1]
Hello,

I have been getting requests to add support for DITN to an upscaling application I created. However, I cannot do that without there being an applicable license. Is it possible for you to add a license to this repository?

Thank you in advance.

**Comment by Sirosky** [comment]
Seconded-- please add a license to this repo! It takes about five minutes.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by yongliuy** [comment]
Hi~

We are very happy that our work is useful for your research and we have added the applicable license.
